# fly.toml app configuration file generated for documind-skander
app = "documind-skander"
primary_region = "cdg"

[build]
  dockerfile = "Dockerfile"

[env]
  APP_ENV = "prod"
  DATA_RAW_DIR = "/src/data/raw"
  CHROMA_PERSIST_DIR = "/src/data/chroma"
  HF_HOME = "/data/huggingface"
  CORS_ORIGINS = "https://documind-orpin.vercel.app,https://documind-skander643s-projects.vercel.app,http://127.0.0.1:5173,http://localhost:5173"
  CORS_ORIGIN_REGEX = "https://documind.*\\.vercel\\.app"
  RATE_LIMIT_PER_MINUTE = "20"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 10
    soft_limit = 5

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "300s"
    method = "GET"
    path = "/health"

[[mounts]]
  source = "documind_hf"
  destination = "/data/huggingface"

[[vm]]
  memory = "4gb"
  cpu_kind = "shared"
  cpus = 2
